"""
Video Generation Service

Format-agnostic video generation pipeline using Sora for scene generation
and Remotion/Motion Canvas for final rendering.
"""

from .types import (
    TrendItemV1,
    ContentBriefV1,
    StoryIRV1,
    FormatPackV1,
    ShotPlanV1,
    AssetManifestV1,
    RenderPlanRemotionV1,
    BeatType,
    Beat,
    Shot,
    TimelineItem,
    Clip,
)
from .story_ir import make_story_ir, validate_story_ir
from .shot_plan import make_shot_plan, estimate_sora_cost
from .render_plan import make_render_plan, validate_render_plan
from .format_selector import select_format, get_available_formats, get_format_by_id
from .sora_runner import (
    SoraRunner,
    run_sora_shot_plan,
    run_sora_shot_plan_sync,
    estimate_generation_cost,
)
from .orchestrator import (
    orchestrate_video_generation,
    orchestrate_video_generation_sync,
    orchestrate_from_dicts,
    preview_orchestration,
    OrchestrationResult,
)
from .voice_engine import (
    VoiceStrategy,
    NarratorConfig,
    BeatSpeechBudget,
    SpeechBudgetResult,
    plan_speech_budget,
    build_voice_policy,
    generate_tts_audio,
    enforce_perspective,
)
from .shot_types import (
    ShotType,
    ShotV2,
    AssetClipV2,
    build_sora_prompt,
    determine_shot_type,
    get_postprocess_hints,
)
from .postprocess import (
    chroma_key_to_alpha,
    extract_audio,
    mute_video,
    mix_audio_tracks,
    get_video_duration,
    get_video_info,
    postprocess_sora_clip,
)
from .render_plan_v2 import (
    RenderPlanRemotionV2,
    LayerV2,
    Transform2D,
    OverlayRules,
    make_render_plan_v2,
    validate_render_plan_v2,
)
from .validator import (
    ValidationResult,
    validate_story_ir as validate_ir,
    validate_shot_plan,
    validate_assets,
    validate_pipeline,
    validate_pre_sora,
)
from .auto_shot_planner import (
    BeatShotPolicy,
    PlannedShot,
    ShotPlanEntry,
    plan_shots_for_beat,
    make_auto_shot_plan,
    get_shots_by_beat,
    estimate_auto_plan_cost,
)
from .full_pipeline import (
    PipelineConfig,
    PipelineResult,
    run_full_pipeline,
    run_full_pipeline_sync,
    preview_pipeline,
)
from .shot_budgeter import (
    ShotBudget,
    BudgetPlan,
    apply_shot_budget,
    make_budgeted_shot_plan,
    estimate_budget_savings,
)
from .plate_manager import (
    PlateVariantPlan,
    PlateUsage,
    RiskReport,
    match_plate_to_beat,
    build_beat_bg_bindings,
    inject_variety,
    detect_plate_anti_patterns,
    fix_anti_patterns,
)
from .media_probe import (
    MediaTiming,
    MediaInfo,
    probe_duration_seconds,
    probe_duration_seconds_sync,
    probe_media_info,
    seconds_to_frames,
    get_media_timing,
    attach_timing_to_clips,
    build_plate_frames_map,
)
from .audio_ducking import (
    DuckingPolicy,
    NarrationCue,
    DEFAULT_DUCKING,
    bg_volume_at_frame,
    generate_volume_keyframes,
    beats_to_narration_cues,
    story_ir_to_narration_cues,
    calculate_ducking_for_render_plan,
    apply_ducking_to_layers,
)
from .char_variety import (
    CharPlacement,
    CharVarietyConfig,
    assign_char_presets_round_robin,
    detect_char_boredom,
    fix_char_placement_boredom,
    create_dramatic_switch_placements,
    merge_char_placements_with_budget,
)
from .remotion_sfx import (
    RemotionSfxMacro,
    RemotionSfxMacros,
    RemotionSfxCue,
    RemotionSfxLayer,
    DEFAULT_REMOTION_MACROS,
    expand_remotion_sfx_cues,
    beats_to_remotion_sfx_cues,
    story_ir_to_remotion_sfx_cues,
    add_sfx_layers_to_render_plan,
    get_remotion_macro_context,
)
from .remotion_budgeter import (
    RemotionBgLayer,
    RemotionCharLayer,
    RemotionBudgetedPlan,
    create_remotion_budgeted_plan,
    bind_assets_to_remotion_layers,
    validate_remotion_assets,
    apply_anti_patterns_fix_to_bindings,
)
from .remotion_time_events import (
    RemotionTimeEvent,
    RemotionVisualReveal,
    RemotionBeatMarker,
    RemotionTimeEventsFile,
    story_ir_to_time_events,
    beats_to_time_events,
    reveals_to_sfx_cues,
    generate_remotion_composition_props,
    save_time_events,
    load_time_events,
)
from .speech_timing import (
    SpeechTimingConfig,
    DEFAULT_SPEECH_TIMING,
    estimate_speech_seconds,
    estimate_beat_duration,
    reconcile_beat_durations,
    reconcile_story_ir_durations,
    get_speech_stats,
)
from .vo_stitcher import (
    BeatNarrationInput,
    NarrationAsset,
    StitchedNarration,
    synthesize_beat_narrations,
    stitch_narration,
    stitch_narration_sync,
    beats_to_narration_inputs,
    story_ir_to_narration_inputs,
    cues_to_ducking_format,
)
from .runtime_budget import (
    RuntimeBudget,
    DEFAULT_RUNTIME_BUDGET,
    CompressionPlan,
    compute_compression_plan,
    apply_compression_to_beats,
    apply_compression_to_ir,
    check_runtime_budget,
    auto_fit_to_budget,
    split_long_beats_in_ir,
)
from .hybrid_format import (
    HybridFormat,
    FormatBlock,
    FormatStyle,
    hybrid_format_to_beats,
    hybrid_format_to_story_ir,
    hybrid_format_to_reveals,
    hybrid_format_to_sfx_cues,
    create_devlog_format,
    create_listicle_format,
    validate_hybrid_format,
    get_hybrid_format_ai_prompt,
)
from .script_classifier import (
    classify_sentence,
    classify_script,
    split_sentences,
    script_to_outline,
    outline_to_beats,
    script_to_story_ir,
)
from .voice_strategy import (
    VoiceStrategy,
    VoiceMode,
    NarratorConfig,
    SoraDialogueConfig,
    VoiceConstraints,
    BeatVoiceFlags,
    DEFAULT_NARRATOR_STRATEGY,
    DEFAULT_SORA_DIALOGUE_STRATEGY,
    DEFAULT_HYBRID_STRATEGY,
    choose_voice_strategy,
    get_voice_strategy_for_format,
    get_beat_voice_flags,
    get_sora_prompt_modifiers,
    apply_voice_strategy_to_shot_plan,
)
from .hf_tts_provider import (
    HFTTSConfig,
    HFTTSProvider,
    TTSRequest,
    create_hf_tts_provider,
    create_tts_provider,
    synthesize_with_provider,
    HF_TTS_MODELS,
)
from .pipeline_orchestrator import (
    PipelineConfig,
    PipelineStep,
    PipelineResult,
    PipelineOrchestrator,
    run_pipeline,
    run_pipeline_sync,
)
from .audio_bus_mixer import (
    AudioTrack,
    AudioBusConfig,
    AudioBusResult,
    mix_audio_bus,
    mix_audio_bus_sync,
    sfx_cues_to_tracks,
    build_audio_bus_from_pipeline,
)
from .render_trigger import (
    RenderConfig,
    RenderResult,
    trigger_render,
    trigger_render_sync,
    trigger_remotion_render,
    trigger_motion_canvas_render,
    trigger_ffmpeg_render,
    save_render_plan,
)
from .domain_dict import (
    DomainDict,
    Domain,
    DomainSignals,
    DEFAULT_DOMAIN_DICT,
    load_domain_dict,
    save_domain_dict,
    classify_sentence_smart,
    get_domain_score,
    extract_domain_keywords,
)
from .duration_normalizer import (
    NormalizeConfig,
    DEFAULT_NORMALIZE_CONFIG,
    normalize_outline_to_duration,
    normalize_story_ir_duration,
    estimate_outline_seconds,
    shorten_explain,
    merge_explains,
)
from .perspective_enforcer import (
    VoiceVars,
    DEFAULT_VOICE_VARS,
    enforce_perspective,
    enforce_perspective_for_beats,
    enforce_perspective_for_story_ir,
    resolve_voice_vars,
    rewrite_to_third_person,
)

__all__ = [
    # Types
    "TrendItemV1",
    "ContentBriefV1",
    "StoryIRV1",
    "FormatPackV1",
    "ShotPlanV1",
    "AssetManifestV1",
    "RenderPlanRemotionV1",
    "BeatType",
    "Beat",
    "Shot",
    "TimelineItem",
    "Clip",
    # Story IR
    "make_story_ir",
    "validate_story_ir",
    # Shot Plan
    "make_shot_plan",
    "estimate_sora_cost",
    # Render Plan
    "make_render_plan",
    "validate_render_plan",
    # Format Selection
    "select_format",
    "get_available_formats",
    "get_format_by_id",
    # Sora Runner
    "SoraRunner",
    "run_sora_shot_plan",
    "run_sora_shot_plan_sync",
    "estimate_generation_cost",
    # Orchestrator
    "orchestrate_video_generation",
    "orchestrate_video_generation_sync",
    "orchestrate_from_dicts",
    "preview_orchestration",
    "OrchestrationResult",
    # Voice Engine
    "VoiceStrategy",
    "NarratorConfig",
    "BeatSpeechBudget",
    "SpeechBudgetResult",
    "plan_speech_budget",
    "build_voice_policy",
    "generate_tts_audio",
    "enforce_perspective",
    # Shot Types
    "ShotType",
    "ShotV2",
    "AssetClipV2",
    "build_sora_prompt",
    "determine_shot_type",
    "get_postprocess_hints",
    # Postprocess
    "chroma_key_to_alpha",
    "extract_audio",
    "mute_video",
    "mix_audio_tracks",
    "get_video_duration",
    "get_video_info",
    "postprocess_sora_clip",
    # Render Plan V2
    "RenderPlanRemotionV2",
    "LayerV2",
    "Transform2D",
    "OverlayRules",
    "make_render_plan_v2",
    "validate_render_plan_v2",
    # Validator
    "ValidationResult",
    "validate_ir",
    "validate_shot_plan",
    "validate_assets",
    "validate_pipeline",
    "validate_pre_sora",
    # Auto Shot Planner
    "BeatShotPolicy",
    "PlannedShot",
    "ShotPlanEntry",
    "plan_shots_for_beat",
    "make_auto_shot_plan",
    "get_shots_by_beat",
    "estimate_auto_plan_cost",
    # Full Pipeline
    "PipelineConfig",
    "PipelineResult",
    "run_full_pipeline",
    "run_full_pipeline_sync",
    "preview_pipeline",
    # Shot Budgeter
    "ShotBudget",
    "BudgetPlan",
    "apply_shot_budget",
    "make_budgeted_shot_plan",
    "estimate_budget_savings",
    # Plate Manager
    "PlateVariantPlan",
    "PlateUsage",
    "RiskReport",
    "match_plate_to_beat",
    "build_beat_bg_bindings",
    "inject_variety",
    "detect_plate_anti_patterns",
    "fix_anti_patterns",
    # Media Probe
    "MediaTiming",
    "MediaInfo",
    "probe_duration_seconds",
    "probe_duration_seconds_sync",
    "probe_media_info",
    "seconds_to_frames",
    "get_media_timing",
    "attach_timing_to_clips",
    "build_plate_frames_map",
    # Audio Ducking
    "DuckingPolicy",
    "NarrationCue",
    "DEFAULT_DUCKING",
    "bg_volume_at_frame",
    "generate_volume_keyframes",
    "beats_to_narration_cues",
    "story_ir_to_narration_cues",
    "calculate_ducking_for_render_plan",
    "apply_ducking_to_layers",
    # Character Variety
    "CharPlacement",
    "CharVarietyConfig",
    "assign_char_presets_round_robin",
    "detect_char_boredom",
    "fix_char_placement_boredom",
    "create_dramatic_switch_placements",
    "merge_char_placements_with_budget",
    # Remotion SFX
    "RemotionSfxMacro",
    "RemotionSfxMacros",
    "RemotionSfxCue",
    "RemotionSfxLayer",
    "DEFAULT_REMOTION_MACROS",
    "expand_remotion_sfx_cues",
    "beats_to_remotion_sfx_cues",
    "story_ir_to_remotion_sfx_cues",
    "add_sfx_layers_to_render_plan",
    "get_remotion_macro_context",
    # Remotion Budgeter
    "RemotionBgLayer",
    "RemotionCharLayer",
    "RemotionBudgetedPlan",
    "create_remotion_budgeted_plan",
    "bind_assets_to_remotion_layers",
    "validate_remotion_assets",
    "apply_anti_patterns_fix_to_bindings",
    # Remotion Time Events
    "RemotionTimeEvent",
    "RemotionVisualReveal",
    "RemotionBeatMarker",
    "RemotionTimeEventsFile",
    "story_ir_to_time_events",
    "beats_to_time_events",
    "reveals_to_sfx_cues",
    "generate_remotion_composition_props",
    "save_time_events",
    "load_time_events",
    # Speech Timing
    "SpeechTimingConfig",
    "DEFAULT_SPEECH_TIMING",
    "estimate_speech_seconds",
    "estimate_beat_duration",
    "reconcile_beat_durations",
    "reconcile_story_ir_durations",
    "get_speech_stats",
    # VO Stitcher
    "BeatNarrationInput",
    "NarrationAsset",
    "StitchedNarration",
    "synthesize_beat_narrations",
    "stitch_narration",
    "stitch_narration_sync",
    "beats_to_narration_inputs",
    "story_ir_to_narration_inputs",
    "cues_to_ducking_format",
    # Runtime Budget
    "RuntimeBudget",
    "DEFAULT_RUNTIME_BUDGET",
    "CompressionPlan",
    "compute_compression_plan",
    "apply_compression_to_beats",
    "apply_compression_to_ir",
    "check_runtime_budget",
    "auto_fit_to_budget",
    "split_long_beats_in_ir",
    # Hybrid Format
    "HybridFormat",
    "FormatBlock",
    "FormatStyle",
    "hybrid_format_to_beats",
    "hybrid_format_to_story_ir",
    "hybrid_format_to_reveals",
    "hybrid_format_to_sfx_cues",
    "create_devlog_format",
    "create_listicle_format",
    "validate_hybrid_format",
    "get_hybrid_format_ai_prompt",
    # Script Classifier
    "classify_sentence",
    "classify_script",
    "split_sentences",
    "script_to_outline",
    "outline_to_beats",
    "script_to_story_ir",
    # Voice Strategy
    "VoiceStrategy",
    "VoiceMode",
    "NarratorConfig",
    "SoraDialogueConfig",
    "VoiceConstraints",
    "BeatVoiceFlags",
    "DEFAULT_NARRATOR_STRATEGY",
    "DEFAULT_SORA_DIALOGUE_STRATEGY",
    "DEFAULT_HYBRID_STRATEGY",
    "choose_voice_strategy",
    "get_voice_strategy_for_format",
    "get_beat_voice_flags",
    "get_sora_prompt_modifiers",
    "apply_voice_strategy_to_shot_plan",
    # HF TTS Provider
    "HFTTSConfig",
    "HFTTSProvider",
    "TTSRequest",
    "create_hf_tts_provider",
    "create_tts_provider",
    "synthesize_with_provider",
    "HF_TTS_MODELS",
    # Pipeline Orchestrator
    "PipelineConfig",
    "PipelineStep",
    "PipelineResult",
    "PipelineOrchestrator",
    "run_pipeline",
    "run_pipeline_sync",
    # Audio Bus Mixer
    "AudioTrack",
    "AudioBusConfig",
    "AudioBusResult",
    "mix_audio_bus",
    "mix_audio_bus_sync",
    "sfx_cues_to_tracks",
    "build_audio_bus_from_pipeline",
    # Render Trigger
    "RenderConfig",
    "RenderResult",
    "trigger_render",
    "trigger_render_sync",
    "trigger_remotion_render",
    "trigger_motion_canvas_render",
    "trigger_ffmpeg_render",
    "save_render_plan",
    # Domain Dictionary
    "DomainDict",
    "Domain",
    "DomainSignals",
    "DEFAULT_DOMAIN_DICT",
    "load_domain_dict",
    "save_domain_dict",
    "classify_sentence_smart",
    "get_domain_score",
    "extract_domain_keywords",
    # Duration Normalizer
    "NormalizeConfig",
    "DEFAULT_NORMALIZE_CONFIG",
    "normalize_outline_to_duration",
    "normalize_story_ir_duration",
    "estimate_outline_seconds",
    "shorten_explain",
    "merge_explains",
    # Perspective Enforcer
    "VoiceVars",
    "DEFAULT_VOICE_VARS",
    "enforce_perspective",
    "enforce_perspective_for_beats",
    "enforce_perspective_for_story_ir",
    "resolve_voice_vars",
    "rewrite_to_third_person",
]
